export const EVENTS = {
	PLAY_RECORDED: "listening-stats:play-recorded",
	SKIP_RECORDED: "listening-stats:skip-recorded",
	HEALTH_CHANGED: "listening-stats:health-changed",
	TRACKING_PAUSED: "listening-stats:tracking-paused",
	TRACKING_RESUMED: "listening-stats:tracking-resumed",
	PROVIDER_CHANGED: "listening-stats:provider-changed",
	STATSFM_CONNECTED: "listening-stats:statsfm-connected",
	STATSFM_DISCONNECTED: "listening-stats:statsfm-disconnected",
	STATSFM_HEALTH_CHANGED: "listening-stats:statsfm-health-changed",
	STATSFM_PROFILE_REFRESHED: "listening-stats:statsfm-profile-refreshed",
	PREFS_CHANGED: "listening-stats:prefs-changed",
	RANK_MODE_CHANGED: "listening-stats:rank-mode-changed",
	DASHBOARD_PERIOD_CHANGED: "listening-stats:dashboard-period-changed",
	OPEN_RECAP: "listening-stats:open-recap",
} as const;
